### PR TITLE
fix: Python examples rewrite

### PR DESCRIPTION
**Pull request by sus2790**

### CODE REVIEW

**Comment by sus2790** [comment]
恐龍Review一下

**Review by dragonyc1002 — CHANGES_REQUESTED** [review]
I have already fixed `classes.py` on the missing argument problem. This part can be deleted.

**Comment by sus2790** [comment]
okie

**Review by dragonyc1002 — APPROVED** [review]

**Comment by sus2790** [comment]
Never gonna say goodbye PR

**Pull request merged**
